---
- name: Install git
  apt: name=git state=present

- name: Install tig
  apt: name=tig state=present

- name: Install git-extras
  apt: name=git-extras state=present

- name: Install tree
  apt: name=tree state=present

- name: Install ag
  apt: name=silversearcher-ag state=present

- name: Install ripgrep from .deb package
  apt:
    deb: https://github.com/BurntSushi/ripgrep/releases/download/11.0.2/ripgrep_11.0.2_amd64.deb

- name: Install fd from .deb package
  apt:
    deb: https://github.com/sharkdp/fd/releases/download/v7.4.0/fd_7.4.0_amd64.deb

- name: Install bat from .deb package
  apt:
    deb: https://github.com/sharkdp/bat/releases/download/v0.12.1/bat_0.12.1_amd64.deb

- name: Install jq
  apt: name=jq state=present

- name: Install unzip
  apt: name=unzip state=present

- name: Install vifm
  apt: name=vifm state=present

- name: Install pandoc
  apt: name=pandoc state=present

- apt_repository:
    repo: ppa:lazygit-team/release
    state: present

- name: install lazygit
  apt: name=lazygit state=present

- name: Install wuzz
  apt: name=wuzz state=present

- name: Install ctags
  apt: name=ctags state=present

# https://kifarunix.com/how-to-install-osquery-on-ubuntu-18-04/
- name: Add osquery signing key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 1484120AC4E9F8A1A577AEEE97A80C63C9D8B80B

- apt_repository:
    repo: "deb [arch=amd64] https://pkg.osquery.io/deb deb main" 
    state: present

- name: install osquery
  apt: name=osquery state=present

# install xsv - utilities for csv from 
# https://github.com/BurntSushi/xsv/releases/latest

# ctags
# exa - https://github.com/ogham/exa
# xsv - https://github.com/BurntSushi/xsv 
# fselect - https://github.com/jhspetersson/fselect

- name: Install autojump
  apt: name=autojump state=present
  register: autojump_status

- name: copy autojump profile
  copy:
    src=/usr/share/autojump/autojump.sh
    dest=/etc/profile.d/autojump.sh
  when: autojump_status.changed
