---
- name: Install git
  apt: name=git state=present

- name: Install tig
  apt: name=tig state=present

- name: Install tree
  apt: name=tree state=present

- name: Install ag
  apt: name=silversearcher-ag state=present

- name: Install ripgrep from .deb package
  apt:
    deb: https://github.com/BurntSushi/ripgrep/releases/download/0.10.0/ripgrep_0.10.0_amd64.deb

- name: Install fd from .deb package
  apt:
    deb: https://github.com/sharkdp/fd/releases/download/v7.2.0/fd_7.2.0_amd64.deb

- apt_repository:
    repo: ppa:neovim-ppa/stable
    update_cache: yes

- name: Install neovim
  apt: name=neovim state=present

- name: Install jq
  apt: name=jq state=present

- name: Install unzip
  apt: name=unzip state=present

- name: Install unzip
  apt: name=unzip state=present

- name: Install autojump
  apt: name=autojump state=present
  register: autojump_status

- name: copy autojump profile
  copy:
    src=/usr/share/autojump/autojump.sh
    dest=/etc/profile.d/autojump.sh
  when: autojump_status.changed
